micronaut:
  application:
    name: forms-manager
  server:
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
jackson:
  serialization:
    indentOutput: false # Use for debug usage such as console
    writeDatesAsTimestamps: false # turn to true if you want number based dates (epoch)
---
datasources:
  default:
    url: jdbc:h2:./build/DB/dbdevDb1;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE # jdbc:h2:~/devDb1;MODE=PostgreSQL;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
---
formValidator:
  client:
    host: http://localhost:8085